spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/utility_dev
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      show_sql: true
      use_sql_comments: true
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    org:
      springframework:
        security: DEBUG
