spring:
  datasource:
    url: jdbc:mysql://sql6.freesqldatabase.com/sql6642122
    username: sql6642122
    password: 7p1C3HZBB3
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        security: DEBUG
