##Database on Azure
#spring:
#  main:
#    allow-bean-definition-overriding: true
#  datasource:
#    url: jdbc:sqlserver://utility-dev-database.database.windows.net:1433;database=utility_dev;user=aleem@utility-dev-database;password=UtilityDB@azure;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
##    username: sql6642195
##    password: BefZL34rdt
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      dialect: org.hibernate.dialect.SQLServerDialect
#
#
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG


#Postgresql Database on Render
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc://postgresql://utility_data_user:980Fjs5PiG2v8RH5RrOI6XSBsJGbktjA@dpg-ctqns3ggph6c73clr5f0-a.oregon-postgres.render.com/utility_data
    username: utility_data
    password: utility_data_user
    continue-on-error: true
    initialization-mode: always
    database: org.postgresql.Driver
  # cloud:
  #   gcp:
  #     project-id: utilityAPI
  #     credentials:
  #       location: file:src/main/resources/utilityapii-a82dae0669b0.json
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL94Dialect

logging:
  level:
    org:
      springframework:
        security: DEBUG




