spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:sqlserver://utility-dev-database.database.windows.net:1433;database=utility_dev;user=aleem@utility-dev-database;password=UtilityDB@azure;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: sql6642195
#    password: BefZL34rdt
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServerDialect


logging:
  level:
    org:
      springframework:
        security: DEBUG



